/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import javax.swing.JOptionPane;

/**
 *
 * @author ChC
 */
public class ComplejidadTecnica extends javax.swing.JFrame {

    /**
     * Creates new form ComplejidadTecnica
     */
    String valido="1";
    public ComplejidadTecnica() {
        initComponents();
        this.setSize(681, 363);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        txttotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        factor = new javax.swing.JLabel();
        factor1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setTitle("Factor Complejidad Tecnica");
        getContentPane().setLayout(null);

        tabla.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Sistema Distribuido",  new Float(2.0), null, null},
                {"Desempeño",  new Float(1.0), null, null},
                {"Eficiencia del usurio final",  new Float(1.0), null, null},
                {"Complejidad del procesamiento interno",  new Float(1.0), null, null},
                {"Reusabilidad del codigo",  new Float(1.0), null, null},
                {"Facilidad de instalacion",  new Float(0.5), null, null},
                {"Facilidad de uso",  new Float(0.5), null, null},
                {"Portabilidad",  new Float(2.0), null, null},
                {"Facilidad de cambio",  new Float(1.0), null, null},
                {"Concurrencia",  new Float(1.0), null, null},
                {"Características especiales de seguridad",  new Float(1.0), null, null},
                {"Provee acceso a terceros",  new Float(1.0), null, null},
                {"Facilidades especiales de entrenamiento a usuarios",  new Float(1.0), null, null}
            },
            new String [] {
                "Descripción", "Peso", "Valor", "SubTotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabla.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tablaPropertyChange(evt);
            }
        });
        jScrollPane3.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setResizable(false);
            tabla.getColumnModel().getColumn(0).setPreferredWidth(200);
            tabla.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(10, 31, 639, 236);

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(300, 280, 100, 23);

        txttotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(txttotal);
        txttotal.setBounds(537, 286, 68, 20);

        jLabel1.setText("Total");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(474, 290, 50, 14);

        factor.setText(" Esencial = 5");
        getContentPane().add(factor);
        factor.setBounds(140, 10, 100, 14);

        factor1.setText(" Irrelevante = 0");
        getContentPane().add(factor1);
        factor1.setBounds(30, 10, 100, 14);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagen2.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 660, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        float total = (float) (0.6 + (0.01*Float.parseFloat(txttotal.getText())));
        Principal.txtCT.setText(Float.toString(total));
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tablaPropertyChange
        // TODO add your handling code here:
        if(validar()) sumaTabla();
        else JOptionPane.showMessageDialog(this, "Rango 0-5");
    }//GEN-LAST:event_tablaPropertyChange
    
    private boolean validar()
    {
        float  b;
        for (int i = 0; i < tabla.getRowCount(); i++) {
            try {
                b=(float) tabla.getValueAt(i, 2);
                if(b>5||b<0) return false;   //modifique aqui ... 
            } catch (Exception e) {
            }
        }
        return true;
    }
    private void sumaTabla()
    {
        float subTotal,a , b;
        float total=0;
        for (int i = 0; i < tabla.getRowCount(); i++) {
            try {
                a=(float) tabla.getValueAt(i, 1);
                b=(float) tabla.getValueAt(i, 2);
                subTotal = a*b;
                total=total+subTotal;
                tabla.setValueAt(subTotal, i, 3);
                txttotal.setText(String.valueOf(total));
            } catch (Exception e) {
            }
        }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComplejidadTecnica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComplejidadTecnica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComplejidadTecnica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComplejidadTecnica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComplejidadTecnica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel factor;
    private javax.swing.JLabel factor1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
