/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author ChC
 */
public class FactorEscala extends javax.swing.JFrame {

    /**
     * Creates new form FactorEscala
     */
    float escala;
    public FactorEscala() {
        initComponents();
        this.setSize(400, 300);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        txt6 = new javax.swing.JTextField();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setTitle("Factores de escala");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("Experiencia");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 48, 55, 14);

        jLabel2.setText("Flexibilidad");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 86, 52, 14);

        jLabel3.setText("Riesgos");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 124, 37, 14);

        jLabel4.setText("Cohesión");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 162, 44, 14);

        jLabel5.setText("Nivel");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 200, 23, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Muy Bajo", "Bajo", "Nominal", "Alto", "Muy Alto", "Extra Alto" }));
        jComboBox1.setSelectedIndex(2);
        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(116, 45, 73, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Muy Bajo", "Bajo", "Nominal", "Alto", "Muy Alto", "Extra Alto" }));
        jComboBox2.setSelectedIndex(2);
        jComboBox2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox2PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(116, 83, 73, 20);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Muy Bajo", "Bajo", "Nominal", "Alto", "Muy Alto", "Extra Alto" }));
        jComboBox3.setSelectedIndex(2);
        jComboBox3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox3PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(jComboBox3);
        jComboBox3.setBounds(116, 121, 73, 20);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Muy Bajo", "Bajo", "Nominal", "Alto", "Muy Alto", "Extra Alto" }));
        jComboBox4.setSelectedIndex(2);
        jComboBox4.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox4PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(jComboBox4);
        jComboBox4.setBounds(116, 159, 73, 20);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Muy Bajo", "Bajo", "Nominal", "Alto", "Muy Alto", "Extra Alto" }));
        jComboBox5.setSelectedIndex(2);
        jComboBox5.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox5PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        getContentPane().add(jComboBox5);
        jComboBox5.setBounds(116, 197, 73, 20);

        txt6.setEditable(false);
        txt6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txt6);
        txt6.setBounds(221, 247, 62, 20);

        txt1.setEditable(false);
        txt1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt1.setText("3.72");
        getContentPane().add(txt1);
        txt1.setBounds(221, 45, 64, 20);

        txt2.setEditable(false);
        txt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt2.setText("3.04");
        getContentPane().add(txt2);
        txt2.setBounds(221, 83, 64, 20);

        txt3.setEditable(false);
        txt3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt3.setText("4.24");
        getContentPane().add(txt3);
        txt3.setBounds(221, 121, 64, 20);

        txt4.setEditable(false);
        txt4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt4.setText("3.29");
        getContentPane().add(txt4);
        txt4.setBounds(221, 159, 64, 20);

        txt5.setEditable(false);
        txt5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt5.setText("4.68");
        getContentPane().add(txt5);
        txt5.setBounds(221, 197, 64, 20);

        jLabel6.setText("Sumtoria");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(116, 250, 42, 14);

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(327, 246, 63, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagen2.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        escala=Float.parseFloat(txt6.getText());
        Principal.txtescala.setText(String.valueOf(escala));
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    private void calcular(){
        escala=Float.parseFloat(txt1.getText())+Float.parseFloat(txt2.getText())+Float.parseFloat(txt3.getText())
                +Float.parseFloat(txt4.getText())+Float.parseFloat(txt5.getText());
        txt6.setText(String.valueOf(escala));
    }
    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if(jComboBox1.getSelectedIndex()==0)
        txt1.setText("6.20");
        else if(jComboBox1.getSelectedIndex()==1)
            txt1.setText("4.96");
        else if(jComboBox1.getSelectedIndex()==2)
            txt1.setText("3.72");
        else if(jComboBox1.getSelectedIndex()==3)
            txt1.setText("2.48");
        else if(jComboBox1.getSelectedIndex()==4)
            txt1.setText("1.24");
        else txt1.setText("0");
        calcular();
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

    private void jComboBox2PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox2PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if(jComboBox2.getSelectedIndex()==0)
        txt2.setText("5.07");
        else if(jComboBox2.getSelectedIndex()==1)
            txt2.setText("4.05");
        else if(jComboBox2.getSelectedIndex()==2)
            txt2.setText("3.04");
        else if(jComboBox2.getSelectedIndex()==3)
            txt2.setText("2.03");
        else if(jComboBox2.getSelectedIndex()==4)
            txt2.setText("1.01");
        else txt2.setText("0");
        calcular();
    }//GEN-LAST:event_jComboBox2PopupMenuWillBecomeInvisible

    private void jComboBox3PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox3PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if(jComboBox3.getSelectedIndex()==0)
        txt3.setText("7.07");
        else if(jComboBox3.getSelectedIndex()==1)
            txt3.setText("5.65");
        else if(jComboBox3.getSelectedIndex()==2)
            txt3.setText("4.24");
        else if(jComboBox3.getSelectedIndex()==3)
            txt3.setText("2.83");
        else if(jComboBox3.getSelectedIndex()==4)
            txt3.setText("1.41");
        else txt3.setText("0");
        calcular();
    }//GEN-LAST:event_jComboBox3PopupMenuWillBecomeInvisible

    private void jComboBox4PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox4PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if(jComboBox4.getSelectedIndex()==0)
        txt4.setText("5.48");
        else if(jComboBox4.getSelectedIndex()==1)
            txt4.setText("4.38");
        else if(jComboBox4.getSelectedIndex()==2)
            txt4.setText("3.29");
        else if(jComboBox4.getSelectedIndex()==3)
            txt4.setText("2.19");
        else if(jComboBox4.getSelectedIndex()==4)
            txt4.setText("1.10");
        else txt4.setText("0");
        calcular();
    }//GEN-LAST:event_jComboBox4PopupMenuWillBecomeInvisible

    private void jComboBox5PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox5PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if(jComboBox5.getSelectedIndex()==0)
        txt5.setText("7.80");
        else if(jComboBox5.getSelectedIndex()==1)
            txt5.setText("6.24");
        else if(jComboBox5.getSelectedIndex()==2)
            txt5.setText("4.68");
        else if(jComboBox5.getSelectedIndex()==3)
            txt5.setText("3.12");
        else if(jComboBox5.getSelectedIndex()==4)
            txt5.setText("1.56");
        else txt5.setText("0");
        calcular();
    }//GEN-LAST:event_jComboBox5PopupMenuWillBecomeInvisible

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        calcular();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FactorEscala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FactorEscala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FactorEscala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FactorEscala.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FactorEscala().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    // End of variables declaration//GEN-END:variables
}
