/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import javax.swing.JOptionPane;

/**
 *
 * @author ChC
 */
public class FactorAmbiente extends javax.swing.JFrame {

    /**
     * Creates new form FactorAmbiente
     */
    public FactorAmbiente() {
        initComponents();
        this.setSize(639,300);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        FA = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        factor = new javax.swing.JLabel();
        factor1 = new javax.swing.JLabel();
        factor2 = new javax.swing.JLabel();
        factor3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setTitle("Factor de Ambiente");
        getContentPane().setLayout(null);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Familiaridad con el Proceso Unificado de Rational",  new Float(1.5), null, null},
                {"Experiencia en el desarrollo de aplicaciones",  new Float(0.5), null, null},
                {"Experiencia  en orientación a objetos",  new Float(1.0), null, null},
                {"Capacidad del jefe de proyecto",  new Float(0.5), null, null},
                {"Motivación",  new Float(1.0), null, null},
                {"Estabilidad de los requerimientos",  new Float(2.0), null, null},
                {"Personal a tiempo parcial",  new Float(-1.0), null, null},
                {"Lenguaje de programación diícil",  new Float(-1.0), null, null}
            },
            new String [] {
                "Descripcion", "Peso", "Valor Asignado", "Sub Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Float.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tablaPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setPreferredWidth(260);
            tabla.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 50, 558, 160);
        getContentPane().add(FA);
        FA.setBounds(500, 220, 76, 20);

        jButton1.setText("Enviar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 220, 120, 23);

        factor.setText("media = 3  ");
        getContentPane().add(factor);
        factor.setBounds(120, 10, 70, 14);

        factor1.setText("Total : ");
        getContentPane().add(factor1);
        factor1.setBounds(430, 220, 70, 14);

        factor2.setText("sin nada  = 0 ");
        getContentPane().add(factor2);
        factor2.setBounds(30, 10, 70, 14);

        factor3.setText("mucho = 5 ");
        getContentPane().add(factor3);
        factor3.setBounds(200, 10, 70, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagen2.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 640, 260);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tablaPropertyChange
        // TODO add your handling code here:
        if(validar())
        {sumaTabla();}
        else JOptionPane.showMessageDialog(this, "Rango 0-5");
    }//GEN-LAST:event_tablaPropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        float a;
        int x=0 ,y=0;
        for (int i = 0; i < 5; i++) {
            try {
               a=(float) tabla.getValueAt(i, 2);
              
                if(a<3) x++; 
            } catch (Exception e) {
            }
        }
        for(int i=6;i<8;i++){
            try {
                a=(float) tabla.getValueAt(i, 2);
                if(a>3) y++;
            } catch (Exception e) {
            }
        }
        String b;
        if(x+y<=2)b="20 horas hombre";
        else if(x+y ==4 || x+y==3) b="28 horas hombre";
        else b="Riesgo de fracaso";
            
        float total = (float) (1.4 + (-0.03*Float.parseFloat(FA.getText())));
        Principal.txtFA.setText(Float.toString(total));
        Principal.txtesfuerzo.setText(b);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private boolean validar()
    {
        float  b;
        for (int i = 0; i < tabla.getRowCount(); i++) {
            try {
                //b=(float) tabla.getValueAt(i, 2);
                 b = Float.parseFloat(tabla.getValueAt(i, 2).toString());
                if(b>5||b<0) return false;
            } catch (Exception e) {
               
            }
        }
        return true;
    }
    
    private boolean validar2(){
        int b = tabla.getSelectedRow();
        
        int x = Integer.parseInt(tabla.getValueAt(b, 2).toString());
        if(x>5){
            return false;
        }else{
            JOptionPane.showMessageDialog(null,"numero Correcto");
            return true;
        }
           
    
    }
    
    private void sumaTabla()
    {
        float subTotal,a , b;
        float total=0;
        for (int i = 0; i < tabla.getRowCount(); i++) {
            try {
                a=(float) tabla.getValueAt(i, 1);
                b=(float) tabla.getValueAt(i, 2);
                subTotal = a*b;
                total=total+subTotal;
                tabla.setValueAt(subTotal, i, 3);
                FA.setText(String.valueOf(total));
            } catch (Exception e) {
            }
        }
        
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FactorAmbiente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FactorAmbiente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FactorAmbiente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FactorAmbiente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FactorAmbiente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FA;
    private javax.swing.JLabel factor;
    private javax.swing.JLabel factor1;
    private javax.swing.JLabel factor2;
    private javax.swing.JLabel factor3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
