/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

/**
 *
 * @author ChC
 */
public class Mantenimiento extends javax.swing.JFrame {

    /**
     * Creates new form Mantenimiento
     */
    private float lineas;
    private float esfuerzo;
    private float exponente;
    private float coeficiente;
    private float costo;
    private int ventana;
    
    
    
    public Mantenimiento() {
        initComponents();
        this.setSize(645, 290);
        this.setLocationRelativeTo(null);
    }

    public void setLineas(float lineas) {
        this.lineas = lineas;
    }

    public void setEsfuerzo(float esfuerzo) {
        this.esfuerzo = esfuerzo;
    }

    public void setExponente(float exponente) {
        this.exponente = exponente;
    }

    public void setCoeficiente(float coeficiente) {
        this.coeficiente = coeficiente;
    }

    public void setCosto(float costo) {
        this.costo = costo;
    }
    

    public void setVentana(int ventana) {        
        this.ventana=ventana;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mod = new javax.swing.JTextField();
        agre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cociente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        esf = new javax.swing.JTextField();
        tdes = new javax.swing.JTextField();
        cost = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(185, 197, 198));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cociente de actividad"));

        jLabel1.setText("Líneas modificadas:");

        jLabel2.setText("Líneas agregadas:");

        mod.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        mod.setText("0");
        mod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                modKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                modKeyTyped(evt);
            }
        });

        agre.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        agre.setText("0");
        agre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                agreKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                agreKeyTyped(evt);
            }
        });

        jLabel3.setText("Líneas totales:");

        total.setEditable(false);

        jLabel4.setText("Cociente");

        cociente.setEditable(false);

        jLabel8.setText("miles");

        jLabel10.setText("miles");

        jLabel11.setText("miles");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mod, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(agre)
                            .addComponent(total)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addComponent(cociente, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(agre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cociente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 30, 300, 200);

        jPanel2.setBackground(new java.awt.Color(185, 197, 198));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));

        jLabel5.setText("Esfuerzo:");

        jLabel6.setText("Tiempo de desarrollo:");

        jLabel7.setText("Costo:");

        esf.setEditable(false);
        esf.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        esf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esfActionPerformed(evt);
            }
        });

        tdes.setEditable(false);
        tdes.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        cost.setEditable(false);
        cost.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(esf, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tdes)
                        .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(esf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(320, 40, 320, 150);

        jButton1.setText("OK!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(390, 200, 100, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imagen2.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-60, -40, 720, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        total.setText(String.valueOf(lineas));
        if(ventana==1)
            this.setTitle("Mantenimiento cocomo BASICO");
        else if(ventana==2)
            this.setTitle("Mantenimiento cocomo INTERMEDIO");
        else this.setTitle("Mantenimiento cocomo II");
    }//GEN-LAST:event_formWindowActivated
    
    private void calcular()
    {
        float a, b;
        if(!mod.getText().isEmpty()&&!agre.getText().isEmpty()){
        a=Float.parseFloat(mod.getText());
        b=Float.parseFloat(agre.getText());
        cociente.setText(String.valueOf((a+b)/lineas));
        a=Float.parseFloat(cociente.getText());
        b=a*esfuerzo;
        esf.setText(String.valueOf(b));
        tdes.setText(String.valueOf((float) (Math.pow(b, exponente)*coeficiente)));
        a=b*costo;
        cost.setText(String.valueOf(a));
        }
    }
    private void modKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modKeyTyped
        // TODO add your handling code here:
        calcular();
    }//GEN-LAST:event_modKeyTyped

    private void modKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modKeyReleased
        // TODO add your handling code here:
        calcular();
    }//GEN-LAST:event_modKeyReleased

    private void agreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agreKeyReleased
       calcular();
    }//GEN-LAST:event_agreKeyReleased

    private void agreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agreKeyTyped
       calcular();
    }//GEN-LAST:event_agreKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        float costo, a ,b;
        if(ventana==1){
            Principal.txtEsfuerzoResultado.setText(esf.getText());
            Principal.txtTiempoResultado.setText(tdes.getText());
                costo=Float.parseFloat(Principal.txtCPM.getText()) * Float.parseFloat(esf.getText());
                Principal.txtCosto.setText(String.valueOf(costo));
                b=Float.parseFloat(esf.getText())*Float.parseFloat(tdes.getText());
                Principal.txtNumDesarrolladores.setText(String.valueOf(b));
                a=(Float.parseFloat(Principal.txtKLDC.getText())*1000)/Float.parseFloat(esf.getText());
                Principal.txtProductividad.setText(String.valueOf(a));
                
        }
        else
            if(ventana==2){
                Principal.txtEsfuerzoResultado1.setText(esf.getText());
                Principal.txtTiempoResultado1.setText(tdes.getText());
                costo=Float.parseFloat(Principal.txtCPM1.getText()) * Float.parseFloat(esf.getText());
                Principal.txtCosto1.setText(String.valueOf(costo));
                b=Float.parseFloat(esf.getText())*Float.parseFloat(tdes.getText());
                Principal.txtNumDesarrolladores1.setText(String.valueOf(b));
                a=(Float.parseFloat(Principal.txtKLDC1.getText())*1000)/Float.parseFloat(esf.getText());
                Principal.txtProductividad1.setText(String.valueOf(a));
                
            }else
            {Principal.txtEsfuerzoResultado2.setText(esf.getText());
            Principal.txtTiempoResultado2.setText(tdes.getText());
            costo=Float.parseFloat(Principal.txtCPM2.getText()) * Float.parseFloat(esf.getText());
                Principal.txtCosto2.setText(String.valueOf(costo));
                b=Float.parseFloat(esf.getText())*Float.parseFloat(tdes.getText());
                Principal.txtNumDesarrolladores2.setText(String.valueOf(b));
                a=(Float.parseFloat(Principal.txtKLDC2.getText())*1000)/Float.parseFloat(esf.getText());
                Principal.txtProductividad2.setText(String.valueOf(a));}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void esfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_esfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mantenimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField agre;
    private javax.swing.JTextField cociente;
    private javax.swing.JTextField cost;
    private javax.swing.JTextField esf;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField mod;
    private javax.swing.JTextField tdes;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
