package Interface;
/**
 *
 * @author Informatico40
 */
public class VentanaCPM extends javax.swing.JFrame {

    private static int CPM1=0,CPM2=0,CPM3=0,CPM4=0,CPM5=0,CPMTotal=0;
    public VentanaCPM() {
        initComponents();
        this.setLocationRelativeTo(null);
        CPMTotal = CPM1+CPM2+CPM3+CPM4+CPM5;
        txtCPMTotal.setText(Integer.toString(CPMTotal));
    
        txtCPMRequerimiento.setText(Integer.toString(CPM1));
        txtCPMAnalisis.setText(Integer.toString(CPM2));
        txtCPMDiseño.setText(Integer.toString(CPM3));
        txtCPMDesarrollo.setText(Integer.toString(CPM4));
        txtCPMPruebas.setText(Integer.toString(CPM5));
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCPMRequerimiento = new javax.swing.JTextField();
        txtCPMAnalisis = new javax.swing.JTextField();
        txtCPMDiseño = new javax.swing.JTextField();
        txtCPMDesarrollo = new javax.swing.JTextField();
        txtCPMPruebas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCPMTotal = new javax.swing.JTextField();
        btnCPMGuardar = new javax.swing.JButton();

        setTitle("costo hombre-mes");

        jPanel1.setBackground(new java.awt.Color(185, 197, 198));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("CPM"));

        jLabel5.setText("Pruebas :");

        jLabel3.setText("Desarrollo :");

        jLabel4.setText("Diseño : ");

        jLabel2.setText("Analisis : ");

        jLabel1.setText("Requerimientos :");

        txtCPMRequerimiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCPMRequerimientoKeyReleased(evt);
            }
        });

        txtCPMAnalisis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCPMAnalisisKeyReleased(evt);
            }
        });

        txtCPMDiseño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCPMDiseñoKeyReleased(evt);
            }
        });

        txtCPMDesarrollo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCPMDesarrolloKeyReleased(evt);
            }
        });

        txtCPMPruebas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCPMPruebasKeyReleased(evt);
            }
        });

        jLabel6.setText("Nuevos Soles");

        jLabel7.setText("TOTAL : ");

        txtCPMTotal.setEditable(false);

        btnCPMGuardar.setText("Enviar");
        btnCPMGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCPMGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCPMPruebas, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCPMDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCPMDiseño, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCPMAnalisis, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCPMRequerimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtCPMTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnCPMGuardar)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCPMRequerimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCPMAnalisis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCPMDiseño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3))
                    .addComponent(txtCPMDesarrollo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCPMPruebas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCPMTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCPMGuardar)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCPMGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCPMGuardarActionPerformed
        this.setVisible(false);
        Principal.txtCPM.setText(txtCPMTotal.getText());
        Principal.txtCPM1.setText(txtCPMTotal.getText());
        Principal.txtCPM2.setText(txtCPMTotal.getText());
    }//GEN-LAST:event_btnCPMGuardarActionPerformed
    
    private void Suma(){
       CPMTotal = CPM1+CPM2+CPM3+CPM4+CPM5;
        txtCPMTotal.setText(Integer.toString(CPMTotal));
    }
    
    private void txtCPMAnalisisKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPMAnalisisKeyReleased
        try {
            CPM2 = Integer.parseInt(txtCPMAnalisis.getText());
            Suma();
        } catch (NumberFormatException e) {
        }
        
    }//GEN-LAST:event_txtCPMAnalisisKeyReleased

    private void txtCPMRequerimientoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPMRequerimientoKeyReleased
        try {
            CPM1 = Integer.parseInt(txtCPMRequerimiento.getText());
            Suma();
        } catch (NumberFormatException e) {}
        
    }//GEN-LAST:event_txtCPMRequerimientoKeyReleased

    private void txtCPMDiseñoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPMDiseñoKeyReleased
        try {
            CPM3 = Integer.parseInt(txtCPMDiseño.getText());
            Suma();
        } catch (NumberFormatException e) {
        }
        
    }//GEN-LAST:event_txtCPMDiseñoKeyReleased

    private void txtCPMDesarrolloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPMDesarrolloKeyReleased
        try {
           CPM4 = Integer.parseInt(txtCPMDesarrollo.getText());
           Suma(); 
        } catch (NumberFormatException e) {
        }
        
    }//GEN-LAST:event_txtCPMDesarrolloKeyReleased

    private void txtCPMPruebasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCPMPruebasKeyReleased
        try {
            CPM5 = Integer.parseInt(txtCPMPruebas.getText());
             Suma();
        } catch (NumberFormatException e) {
        }
        
    }//GEN-LAST:event_txtCPMPruebasKeyReleased
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCPM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCPM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCPM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCPM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCPM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCPMGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCPMAnalisis;
    private javax.swing.JTextField txtCPMDesarrollo;
    private javax.swing.JTextField txtCPMDiseño;
    private javax.swing.JTextField txtCPMPruebas;
    private javax.swing.JTextField txtCPMRequerimiento;
    private javax.swing.JTextField txtCPMTotal;
    // End of variables declaration//GEN-END:variables
}
