/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Informatico40
 */
public class Welcome extends javax.swing.JFrame {

    private int auxiliar = 0;
    private boolean realizado = false;
    hilo ejecutar = new hilo();
    public Welcome() {
        initComponents();
        
        Welcome.this.getRootPane().setOpaque(false);        
        Welcome.this.getContentPane ().setBackground (new Color (0, 0, 0, 0));
        Welcome.this.setBackground (new Color (0, 0, 0, 0)); 
        Welcome.this.setSize(500,375);
        this.setResizable(false);
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mensaje = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        barra = new javax.swing.JProgressBar();
        Mensaje2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 375));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        Mensaje.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        Mensaje.setForeground(new java.awt.Color(255, 255, 255));
        Mensaje.setText("BIENVENIDO ");
        getContentPane().add(Mensaje);
        Mensaje.setBounds(180, 100, 132, 40);

        text.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        text.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(text);
        text.setBounds(40, 210, 270, 30);
        getContentPane().add(barra);
        barra.setBounds(40, 254, 420, 30);

        Mensaje2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        Mensaje2.setForeground(new java.awt.Color(255, 255, 255));
        Mensaje2.setText("ESTIMACION DE COSTOS DE SOFTWARE");
        getContentPane().add(Mensaje2);
        Mensaje2.setBounds(60, 50, 390, 40);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inicio.jpg"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(0, 0, 500, 375);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
         if(realizado == false){
        realizado = true;
        barra.setMaximum(49);
        barra.setMinimum(0);
        barra.setStringPainted(true);
        ejecutar.start();
        }
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    private class hilo extends Thread{
    @Override
    public void run(){
        try {while(true){
            auxiliar++;
            barra.setValue(auxiliar);
            repaint();
            switch(auxiliar){
                case 3:
                    text.setText("Cargando programa...");
                    break;
                case 20:
                    text.setText("Leyendo preferencias");
                    break;
                case 50:
                    text.setText("Carga finalizada");
                    break;
                case 60:
                    Principal objeto = new Principal();
                    objeto.setVisible(true);
                    objeto.setLocationRelativeTo(Welcome.this);
                    Welcome.this.dispose();
                    break;                    
            }
            Thread.sleep(100);}
        } catch (InterruptedException ex) {
            Logger.getLogger(Welcome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Mensaje;
    private javax.swing.JLabel Mensaje2;
    private javax.swing.JProgressBar barra;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}

